import img1 from '../assets/client1.svg';
export const jobs = [
    {
        id:1,
        username:'hr_name',
        role:"Developer",
        type:"Full time",
        head:"Web developer",
        body:"Create and maintain functional websites for online presence and interaction.",
        location:'Banglore',
        salary:"50-80k",
        logo:'',
        company:"Google"
    },
];

export const applications = [
    {
        id:1,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:2,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:3,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:4,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:5,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:6,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:7,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:8,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    },
    {
        id:9,
        img:img1,
        name:'Robert Anderson',
        title:'Graphic designer',
        rating:'5',
        bio:'"Versatile team player with strong initiative."',
        resume:'https://www.w3schools.com/react/react_router.asp',
        status:'',
    }
];